pipeline {
  agent {
        kubernetes {
            label 'kaniko-agent'
            defaultContainer 'jnlp'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
      - cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
"""
        }
    }

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO = '928413605425.dkr.ecr.us-east-1.amazonaws.com/full-stack-backend'
        CLUSTER_NAME = 'my-eks-cluster'
        DEPLOYMENT_NAME = 'fastapi-deployment'
       
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/ayanshaikh0525/full-stack-nextjs-fastapi-app.git'
            }
        }

        
       stage('Build & Push Docker Image with Kaniko') {
            steps {
                container('kaniko') {
                    sh """
                    /kaniko/executor \
                      --dockerfile=\$WORKSPACE/Dockerfile \
                      --context=\$WORKSPACE \
                      --destination=\$ECR_REPO:latest \
                      --skip-tls-verify
                    """
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-jenkins']]) {
                    sh '''
                    # Update kubeconfig for kubectl
                    aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

                    # Update the deployment image
                    kubectl set image deployment/$DEPLOYMENT_NAME fastapi-container=$ECR_REPO:latest

                    # Optional: rollout status check
                    kubectl rollout status deployment/$DEPLOYMENT_NAME
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
