pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        ECR_REPO = "928413605425.dkr.ecr.${AWS_REGION}.amazonaws.com/full-stack-backend"
        IMAGE_TAG = "latest"
        CLUSTER_NAME = "my-eks-cluster"
    }

    stages {

        stage('Clone-Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/ayanshaikh0525/full-stack-nextjs-fastapi-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd fastapi_backend
                docker build -t my-app .
                
                '''
            }
        }

        stage('Tag Image') {
            steps {
                sh 'docker tag my-app:latest $ECR_REPO:$IMAGE_TAG'
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin $ECR_REPO
                '''
            }
        }

        stage('Push to ECR') {
            steps {
                sh 'docker push $ECR_REPO:$IMAGE_TAG'
            }
        }

        stage('Deploy to EKS') {
            steps {

                         sh '''
            aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

            echo "🚀 Updating deployment image..."
            kubectl set image deployment/fastapi-deployment fastapi=$ECR_REPO:$IMAGE_TAG --record
            kubectl rollout restart deployment/fastapi-deployment
            echo "📜 Rollout history:"
            kubectl rollout history deployment/fastapi-deployment

            echo "⏳ Waiting for rollout..."
            if ! kubectl rollout status deployment/fastapi-deployment --timeout=120s; then
                echo "❌ Rollout failed! Rolling back..."
                kubectl rollout undo deployment/fastapi-deployment
                exit 1
            fi

            echo "✅ Deployment successful!"
            '''
            }
        }
    }
}
