name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "nextjs-frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v3
        with:
          path: .
          
      - name: debug and run
        run: |
          pwd
          ls -la 
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: cd nextjs-frontend && npm install

      - name: Build
        run: cd nextjs-frontend && npm run build

      - name: Deploy to Vercel
        run: |
          cd nextjs-frontend
          
          rm -rf .vercel
          
          npm install -g vercel@32.6.0
          
          npx vercel --prod \
          --token ${{ secrets.VERCEL_TOKEN }} \
          --yes
